name: On Pull Request To Main

on:
  pull_request:
    branches:
      - main

jobs:
  job1:
    name: Analyze, Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: dotnet Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: install cake
      run: dotnet tool restore

    - name: dotnet Cake
      run: dotnet cake

    - name: CodeCov
      uses: codecov/codecov-action@v3.1.1
      with:
        files: ./tests/CoreBox.Tests/coverage.opencover.xml
        fail_ci_if_error: true

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}