name: On Pull Request To Main

on:
  pull_request:
    branches:
      - main

jobs:
  job1:
    name: Analyze, Build and Test
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@master

    - name: dotnet Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: install cake
      run: dotnet tool restore

    - name: dotnet Cake
      run: dotnet cake

    - name: CodeCov
      uses: codecov/codecov-action@v3.1.1
      with:
        files: ./tests/CoreBox.Tests/coverage.opencover.xml
        fail_ci_if_error: true

    - name: Setup Sonnar Scanner Tool
      run: dotnet tool install --global dotnet-sonarscanner

    - name: SonarCloud Scan
      run: |
        dotnet-sonarscanner begin /k:"lucassvasconcelos_corebox" /o:"lucassvasconcelos" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
        dotnet build
        dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}