name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  job1:
    name: Update Version and Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: dotnet Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: GitVersion Setup
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: GitVersion Execute
      uses: gittools/actions/gitversion/execute@v0.9.7
      id: gitversion
      with:
        useConfigFile: true

    - name: Package Publish
      run: dotnet nuget push -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_TOKEN }} ./src/CoreBox/bin/Release/*.nupkg --skip-duplicate